version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secops-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    restart: always
